### ISSUE TITLE
Getting Object of class Base could not be converted to string

### ISSUE THREAD

**Issue by GhaziTriki** [ikkez/f3-mailer#2]
I am using the Mailer class within F3 and getting this error

`Object of class Base could not be converted to string`

![image](https://user-images.githubusercontent.com/4991088/52309063-4bd06c00-299f-11e9-8653-03b48e387660.png)

The reason is that in this line `base.php:1823	source  ReflectionClass->newInstanceArgs(arguments)` We are giving the F3 instance as first parameter.

**Comment by GhaziTriki** [comment]
Not sure, it may be a routing issue. Can you please add directive for configuring nginx and httpd for this library?

**Comment by ikkez** [comment]
Hey. The error is clear here.. you said you give the F3 instance as 1st parameter, thought this class expects a string value, being the charset encoding: https://github.com/ikkez/f3-mailer/blob/master/mailer.php#L35

```php
$mailer = new Mailer('UTF-8');
```

**Comment by GhaziTriki** [comment]
I am just doing `$mailer = new Mailer()`, however this error is happening when I do `initTracking`

**Comment by GhaziTriki** [comment]
Please find below the stack trace

![image](https://user-images.githubusercontent.com/4991088/52444201-fa9fb400-2b27-11e9-84a0-f3426cf2cbaa.png)

**Comment by ikkez** [comment]
should be fixed now in the latest commit.
